# Shapiro: A Handsome Helper for R
# Copyright (C) 2018 D. Michael Parrish
# 
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <https://www.gnu.org/licenses/>.
#
# END OF COPYRIGHT NOTICE
#
#

Font1 <- list(
    Ink=matrix(T),
    Paper=matrix(F),
    Width=8L,
    Height=16L,
    DotWidth=2L,
    
    NULL
)

Font1$NarrowSpace <- rbind(rep(list(Font1$Paper), Font1$Height))
Font1$Space <- matrix(unlist(rep(list(Font1$NarrowSpace), Font1$Width)), nrow=Font1$Width)
Font1$CenterDot <- do.call(
    rbind,
    c(
        rep(list(Font1$Paper), (Font1$Width - Font1$DotWidth) %/% 2),
        rep(list(Font1$Ink  ), Font1$DotWidth),
        rep(list(Font1$Paper), (Font1$Width - Font1$DotWidth) %/% 2)
))

Font1$dotsandnot2character <- words.h %O% `%//%` %O% (argswap(strsplit) %<=% "") %O% unlist %O% (`!=` %<=% ".") %O% (im.v %^% list(ncol=Font1$Width))

Font1$Slate <- '
........
........
........
........
........
........
........
........
........
........
........
........
........
........
........
........'

Font1$Number0 <- '
........
..88888.
.88...88
.88...88
.88.8.88
.88...88
.88...88
..88888.
........
........' % % Font1$dotsandnot2character # % % image

blank.slate()
DPI=96
par(usr=DPI*as.vector(matrix(c(0, 0, par()$din), ncol=2, byrow=T)))
par()$din
par()$usr
stamp(!Font1$Number0, 2*Font1$Width, 2*ncol(Font1$Number0), 200, 200, col=c(BLK, WHT))
formals(stamp)

Font1$Comma <-
words.h('
........
...88...
...88...
...88...




Font1$LeftStaff <- 


FONT1.DATA <-"
APOSTROPHE
...88...
...88...
...88...
........

COMMA
........
...88...
...88...
...88...

PERIOD
........
...88...
...88...

PIPE
...88...
...88...
...88...
...88...
...88...
...88...
...88...
...88...

COLON
...88...
...88...
........
........
...88...
...88...

SEMI-COLON
...88...
...88...
........
........
...88...
...88...
...88...

QUOTES
.88..88.
.88..88.
.88..88.
........
"
